### ISSUE TITLE
ModuleNotFoundError: No module named 'python_socks'

### ISSUE THREAD

**Issue by tuqpa** [DIGITALCRIMINALS/UltimaScraperAPI#1]
hey when i start script i get this error 
Traceback (most recent call last):
  File "/Users/mac/Music/test/UltimaScraperAPI/test.py", line 3, in <module>
    import ultima_scraper_api
  File "/Users/mac/Music/test/UltimaScraperAPI/ultima_scraper_api/__init__.py", line 3, in <module>
    import ultima_scraper_api.apis.fansly.classes as fansly_classes
  File "/Users/mac/Music/test/UltimaScraperAPI/ultima_scraper_api/apis/fansly/classes/__init__.py", line 1, in <module>
    from ultima_scraper_api.apis.fansly.classes import (
  File "/Users/mac/Music/test/UltimaScraperAPI/ultima_scraper_api/apis/fansly/classes/user_model.py", line 8, in <module>
    from ultima_scraper_api.apis import api_helper
  File "/Users/mac/Music/test/UltimaScraperAPI/ultima_scraper_api/apis/api_helper.py", line 22, in <module>
    import python_socks
ModuleNotFoundError: No module named 'python_socks'

**Comment by DIGITALCRIMINALS** [comment]
Install the requirements
