### ISSUE TITLE
Return self.directory_manager_users[user_id]

### ISSUE THREAD

**Issue by ChillyP** [DIGITALCRIMINALS/UltimaScraperAPI#11]
Hi DC,

Running the latest commits and running into the error below, not sure if its an issue with USAPI or USC, going to rerun but ignore messages. I've replaced my user_id with #######.

```
Processing Scraped Messages
  0%|                                                                                                                                                | 1/7255 [00:02<08:26:31,  2.94s/it]Traceback (most recent call last):
  File "C:\Users\user\Documents\GitHub\UltimaScraper\start_us.py", line 62, in <module>
    asyncio.run(main())
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\user\Documents\GitHub\UltimaScraper\start_us.py", line 44, in main
    _api = await USR.start(
  File "C:\Users\user\Documents\GitHub\UltimaScraper\ultima_scraper\ultima_scraper.py", line 50, in start
    await self.start_datascraper(datascraper)
  File "C:\Users\user\Documents\GitHub\UltimaScraper\ultima_scraper\ultima_scraper.py", line 137, in start_datascraper
    await datascraper.datascraper.api.job_manager.process_jobs()
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-BeqlQt5t-py3.10\lib\site-packages\ultima_scraper_api\managers\job_manager\job_manager.py", line 45, in process_jobs
    await asyncio.create_task(self.__worker())
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-BeqlQt5t-py3.10\lib\site-packages\ultima_scraper_api\managers\job_manager\job_manager.py", line 53, in __worker
    await job.task
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-BeqlQt5t-py3.10\lib\site-packages\ultima_scraper_collection\modules\module_streamliner.py", line 195, in prepare_scraper
    await self.process_scraped_content(
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-BeqlQt5t-py3.10\lib\site-packages\ultima_scraper_collection\modules\module_streamliner.py", line 231, in process_scraped_content
    unrefined_set: list[dict[str, Any]] = await tqdm_asyncio.gather(
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-BeqlQt5t-py3.10\lib\site-packages\tqdm\asyncio.py", line 79, in gather
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-BeqlQt5t-py3.10\lib\site-packages\tqdm\asyncio.py", line 79, in <listcomp>
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 571, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-BeqlQt5t-py3.10\lib\site-packages\tqdm\asyncio.py", line 76, in wrap_awaitable
    return i, await f
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-BeqlQt5t-py3.10\lib\site-packages\ultima_scraper_collection\managers\datascraper_manager\datascrapers\onlyfans.py", line 64, in media_scraper
    reformat_item = reformat_manager.prepare_reformat(asset)
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-BeqlQt5t-py3.10\lib\site-packages\ultima_scraper_renamer\reformat.py", line 369, in prepare_reformat
    download_path = self.filesystem_manager.get_directory_manager(
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-BeqlQt5t-py3.10\lib\site-packages\ultima_scraper_collection\managers\filesystem_manager.py", line 55, in get_directory_manager
    return self.directory_manager_users[user_id]
KeyError: #######
  0%|▏                                                                                                                                                 | 63/7255 [00:04<07:45, 15.53it/s]
```

**Comment by ChillyP** [comment]
Hi DC,

I still get this issue with the latest update.
