### ISSUE TITLE
KeyError: 'hasMore'

### ISSUE THREAD

**Issue by fl4shforward** [DIGITALCRIMINALS/UltimaScraperAPI#12]
Hi!

Running latest commit on my container https://github.com/fl4shforward/onlyfans-docker
I'm having the following issue:

```
Skipping virtualenv creation, as specified in config file.
[2023-06-01 14:56:09] Assigning Jobs
Traceback (most recent call last):
  File "/usr/src/app/./start_us.py", line 62, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/src/app/./start_us.py", line 44, in main
    _api = await USR.start(
  File "/usr/src/app/ultima_scraper/ultima_scraper.py", line 50, in start
    await self.start_datascraper(datascraper)
  File "/usr/src/app/ultima_scraper/ultima_scraper.py", line 137, in start_datascraper
    await datascraper.datascraper.api.job_manager.process_jobs()
  File "/usr/local/lib/python3.10/site-packages/ultima_scraper_api/managers/job_manager/job_manager.py", line 45, in process_jobs
    await asyncio.create_task(self.__worker())
  File "/usr/local/lib/python3.10/site-packages/ultima_scraper_api/managers/job_manager/job_manager.py", line 53, in __worker
    await job.task
  File "/usr/local/lib/python3.10/site-packages/ultima_scraper_collection/modules/module_streamliner.py", line 169, in prepare_scraper
    unrefined_set: list[message_types | Any] = await user.get_messages()
  File "/usr/local/lib/python3.10/site-packages/ultima_scraper_api/apis/onlyfans/classes/user_model.py", line 344, in get_messages
    has_more = results[-1]["hasMore"] if results else False
KeyError: 'hasMore'
```

**Comment by fl4shforward** [comment]
Seems fixed in latest commit https://github.com/DIGITALCRIMINALS/UltimaScraperAPI/commit/77422cc9b8b32c1ebb5485160de24ff97721db51

**Comment by DIGITALCRIMINALS** [comment]
Turns out it was because a user was deleted, so the script just skips them. 
Their paid content will still download though.
